### PR TITLE
Added support for Symfony 7.x

### PR DESCRIPTION
**Pull request by nightio**

### CODE REVIEW

**Comment by GromNaN** [comment]
Thank you! The tests are failing, do you want to have a look?

**Comment by nightio** [comment]
@GromNaN I modified the tests. 
Could you run it again?

It works on my branch https://github.com/nightio/metrics/actions/runs/9959328699/job/27515923520

If you be able to merge the PR, please create new version :)

**Comment by GromNaN** [comment]
Thank you @nightio. Very appreciated.

**Comment by nightio** [comment]
@GromNaN no problem 🙂

Could you create a release?

**Comment by GromNaN** [comment]
Done [v2.1.0](https://github.com/prismamedia/metrics/releases/tag/v2.1.0)

**Comment by nightio** [comment]
Thanks 👍🏻

**Pull request merged**
