### PR TITLE
Improved docker compose for tests

### PR DESCRIPTION
**Pull request by nightio**

### CODE REVIEW

**Comment by GromNaN** [comment]
How does it improve? I can see config becoming more complicated, but I'm not sure there's much point in improving test performance on such a small library.

**Comment by nightio** [comment]
I just spent 10 minutes to review my previous approach and change it.
It the changed version, docker will not touch local files anymore which is better for development. It uses anonymous volumes and container file system for any modified files.

However, you can close the PR if you wish.
I made it for fun 🙂

**Comment by GromNaN** [comment]
Okay, have it your way. While you are at it, you could exclude docker files in [.gitattributes](https://github.com/prismamedia/metrics/blob/2.x/.gitattributes). Thank you.

**Comment by nightio** [comment]
Done.
I also changed `phpunit.xml` to `phpunit.xml.dist` in `.gitattributes`

**Review by GromNaN — APPROVED** [review]

**Pull request merged**
